#!/usr/bin/env python3
"""
draft_reply.py - Draft email response logic for cloud environment.

This module generates draft email replies based on templates and context.
Drafts are created in Needs_Action with yaml frontmatter for handover.
"""

import os
import re
from pathlib import Path
from datetime import datetime
from typing import Dict, Optional, Any
import yaml


class DraftReplyGenerator:
    """Generate draft email replies for handover to local agent."""

    def __init__(self, vault_path: str, templates_path: Optional[str] = None):
        """
        Initialize draft reply generator.

        Args:
            vault_path: Path to AI_Employee_Vault
            templates_path: Optional path to email templates
        """
        self.vault_path = Path(vault_path)
        self.drafts_folder = self.vault_path / "Pending_Approval"
        self.templates_path = Path(templates_path) if templates_path else self.vault_path / "templates" / "email"

        # Ensure directories exist
        self.drafts_folder.mkdir(parents=True, exist_ok=True)
        self.templates_path.mkdir(parents=True, exist_ok=True)

    def generate_draft(
        self,
        action: Dict[str, Any],
        context: Optional[Dict[str, Any]] = None
    ) -> Path:
        """
        Generate a draft email response.

        Args:
            action: Action dictionary with email details
            context: Additional context (sender info, history, etc.)

        Returns:
            Path to the created draft file
        """
        context = context or {}

        # Determine template to use
        template_name = self._select_template(action, context)
        template_path = self.templates_path / f"{template_name}.md"

        # Load template or use default
        if template_path.exists():
            with open(template_path, 'r') as f:
                email_template = f.read()
        else:
            email_template = self._get_default_template(action)

        # Fill template with action and context data
        email_body = self._fill_template(email_template, action, context)

        # Generate draft metadata
        timestamp = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
        draft_id = f"email_draft_{action.get('action_id', 'unknown')}_{timestamp}"

        # Construct file paths
        draft_file = self.drafts_folder / f"{draft_id}.yaml"

        # Prepare draft metadata
        draft_metadata = {
            'draft_id': draft_id,
            'source_action': action.get('action_id'),
            'type': 'email_draft',
            'mode': 'DRAFT',  # CRITICAL: Draft mode indicator
            'recipient': action.get('email', context.get('recipient')),
            'subject': self._generate_subject(action, context),
            'timestamp': datetime.utcnow().isoformat(),
            'agent': os.getenv('CLOUD_AGENT_ID', 'cloud-agent'),
            'requires_approval': True,
            'cloud_environment': True
        }

        # Add any additional context
        if context:
            draft_metadata['context'] = context

        # Create draft file with YAML frontmatter
        draft_content = f"""---
{yaml.dump(draft_metadata, default_flow_style=False)}
---

## Email Draft

**⚠ DRAFT MODE - NOT SENT ⚠**

This is a **DRAFT** email response generated by the cloud agent.
**The email has NOT been sent** and requires approval before delivery.

### Draft Details

- **Recipient**: {draft_metadata['recipient']}
- **Subject**: {draft_metadata['subject']}
- **Generated**: {draft_metadata['timestamp']}
- **Agent**: {draft_metadata['agent']}
- **Mode**: CLOUD DRAFT

---

## Email Body

{email_body}

---

## Approval Instructions

To approve and send this email:
1. Review the content carefully
2. Verify recipient address
3. Check for sensitive information
4. Run: python send_draft_email.py /path/to/this/file

To reject:
1. Move this file to the Rejected folder
2. Optional: Add feedback in the file

***

**This draft was generated in a cloud environment and requires local approval.**
"""

        # Write draft file
        with open(draft_file, 'w') as f:
            f.write(draft_content)

        print(f"✓ Generated draft: {draft_file}")
        print(f"  Draft ID: {draft_id}")
        print(f"  Recipient: {draft_metadata['recipient']}")
        print(f"  Subject: {draft_metadata['subject']}")

        return draft_file

    def _select_template(self, action: Dict[str, Any], context: Dict[str, Any]) -> str:
        """Select appropriate template for the email."""
        action_type = action.get('type', 'general')

        # Check for specific templates
        if action_type == 'invoice':
            return 'invoice_response'
        elif action_type == 'payment':
            return 'payment_confirmation'
        elif action_type == 'urgent':
            return 'urgent_reply'
        elif 'client_followup' in action.get('tags', []):
            return 'client_followup'

        # Use action type if template exists, otherwise default
        template_name = action_type
        template_path = self.templates_path / f"{template_name}.md"
        return template_name if template_path.exists() else 'general'

    def _get_default_template(self, action: Dict[str, Any]) -> str:
        """Get default email template when specific template not found."""
        return """Hello,

Thank you for your email regarding: {{topic}}

I've reviewed your request and here's my response:

{{response_body}}

Please let me know if you need any further assistance.

Best regards,
{{sender_name}}
"""

    def _fill_template(self, template: str, action: Dict[str, Any], context: Dict[str, Any]) -> str:
        """Fill template with action and context data."""
        # Simple template variable replacement
        # In production, use Jinja2 or similar

        # Merge action and context for template variables
        template_vars = {**action, **context}

        # Fill known variables
        for key, value in template_vars.items():
            if isinstance(value, str):
                template = template.replace(f"{{{{{key}}}}}", value)

        # Add defaults if variables remain
        template = template.replace("{{sender_name}}", "AI Employee")
        template = template.replace("{{response_body}}", action.get('content', 'Thank you for contacting us.'))
        template = template.replace("{{topic}}", action.get('title', 'your inquiry'))

        return template

    def _generate_subject(self, action: Dict[str, Any], context: Dict[str, Any]) -> str:
        """Generate email subject line."""
        if 'subject' in action:
            return f"RE: {action['subject']}"
        elif 'title' in action:
            return f"Re: {action['title']}"

        # Default subjects based on type
        action_type = action.get('type', 'general')
        subjects = {
            'invoice': 'Invoice Response',
            'payment': 'Payment Confirmation',
            'urgent': 'Urgent: Response Required',
            'general': 'Response to Your Inquiry'
        }

        return subjects.get(action_type, 'Response')


def main():
    """CLI entry point for generating drafts."""
    import sys

    if len(sys.argv) < 4:
        print("Usage: python draft_reply.py <vault_path> <action_file> <context_json>")
        print("Example: python draft_reply.py AI_Employee_Vault action.yaml '{\"recipient\": \"test@example.com\"}'")
        sys.exit(1)

    vault_path = sys.argv[1]
    action_file = Path(sys.argv[2])
    context_json = sys.argv[3] if len(sys.argv) > 3 else '{}'

    if not action_file.exists():
        print(f"Error: Action file not found: {action_file}")
        sys.exit(1)

    # Load action
    try:
        with open(action_file, 'r') as f:
            action_content = f.read()

        # Extract YAML frontmatter
        if '---' in action_content:
            import yaml
            parts = action_content.split('---', 2)
            action = yaml.safe_load(parts[1])
        else:
            print("Error: Invalid action file format (no YAML frontmatter)")
            sys.exit(1)
    except Exception as e:
        print(f"Error loading action file: {e}")
        sys.exit(1)

    # Load context
    try:
        import json
        context = json.loads(context_json)
    except Exception as e:
        print(f"Error parsing context JSON: {e}")
        sys.exit(1)

    # Generate draft
    generator = DraftReplyGenerator(vault_path)
    draft_path = generator.generate_draft(action, context)

    print(f"✓ Draft created: {draft_path}")
    print(f"  Mode: DRAFT ONLY (requires approval)")
    print(f"  Next: Review and approve in Pending_Approval/")


if __name__ == '__main__':
    main()
