"""
Plan Manager.

Responsible for analyzing Action Files and generating Execution Plans.
This is the "Reasoning" step of the AI Employee loop.

Per hackathon requirements: "Claude Code acts as the reasoning engine...
It uses its File System tools to read your tasks and write reports."

The plan manager now uses:
1. Claude Code CLI (Primary Intelligence)
2. Qwen Code Agent (Fallback Intelligence)
3. Templates (Last Resort Failsafe)
"""

import time
import hashlib
import yaml
import re
import os
from typing import Dict, Any, Optional
from dotenv import load_dotenv
from src.lib.logging import get_logger
from src.lib.vault import vault

# Load environment variables
load_dotenv()

# Import Claude invoker
try:
    from src.orchestration.claude_invoker import get_claude_invoker, ClaudeInvoker
    CLAUDE_INVOKER_AVAILABLE = True
except ImportError:
    CLAUDE_INVOKER_AVAILABLE = False

# Import Qwen invoker
try:
    from src.orchestration.qwen_invoker import get_qwen_invoker, QwenInvoker
    QWEN_INVOKER_AVAILABLE = True
except ImportError:
    QWEN_INVOKER_AVAILABLE = False


class PlanManager:
    def __init__(self, use_ai: bool = True):
        """
        Initialize the Plan Manager.
        """
        self.logger = get_logger("plan_manager")
        self.sensitive_keywords = ["email", "pay", "send", "post", "delete", "archive", "transfer", "invite"]

        self.use_ai = use_ai
        self.claude_invoker: Optional[ClaudeInvoker] = None
        self.qwen_invoker: Optional[QwenInvoker] = None

        if use_ai:
            # Initialize Claude
            if CLAUDE_INVOKER_AVAILABLE:
                try:
                    self.claude_invoker = get_claude_invoker(vault_path=str(vault.root))
                    if self.claude_invoker.is_available:
                        self.logger.info("Claude Code: ENABLED (Primary)")
                    else:
                        self.logger.info("Claude Code: NOT FOUND")
                except Exception as e:
                    self.logger.error(f"Failed to init Claude: {e}")

            # Initialize Qwen
            # Initialize Qwen
            if QWEN_INVOKER_AVAILABLE:
                try:
                    self.qwen_invoker = get_qwen_invoker(vault_path=str(vault.root))
                    if self.qwen_invoker.is_available:
                        self.logger.info("Qwen Code Agent: ENABLED (Fallback)")
                    else:
                        self.logger.info("Qwen Code Agent: NOT FOUND")
                except Exception as e:
                    self.logger.error(f"Failed to init Qwen: {e}")

    def create_plan_from_action(self, action_file_path: Any) -> str:
        """
        Read an action file and generate a plan.
        Priority: Claude -> Qwen -> Template
        """
        try:
            content = vault.read_file(action_file_path)

            # Parse frontmatter
            parts = content.split('---', 2)
            if len(parts) < 3:
                self.logger.error("Invalid action file format")
                return ""

            frontmatter = yaml.safe_load(parts[1])
            body = parts[2]
            plan_content = None
            used_engine = "template"

            # Determine primary engine from environment
            primary_engine = os.environ.get("REASONING_ENGINE", "qwen").lower()
            
            # 1. Try Primary Engine
            if primary_engine == "qwen" and self.qwen_invoker and self.qwen_invoker.is_available:
                self.logger.info("Preferred Engine: Qwen Code Agent. Attempting...")
                plan_content = self.qwen_invoker.invoke_for_planning(
                    action_content=content,
                    action_metadata=frontmatter
                )
                if plan_content:
                    used_engine = "qwen"
                    self.logger.info("Plan generated by Qwen Code Agent")

            elif primary_engine == "claude" and self.claude_invoker and self.claude_invoker.is_available:
                self.logger.info("Preferred Engine: Claude Code. Attempting...")
                plan_content = self.claude_invoker.invoke_for_planning(
                    action_content=content,
                    action_metadata=frontmatter
                )
                if plan_content:
                    used_engine = "claude"
                    self.logger.info("Plan generated by Claude Code")

            # 2. Fallback (Swap engines)
            if not plan_content:
                if primary_engine == "qwen" and self.claude_invoker and self.claude_invoker.is_available:
                    self.logger.info("Qwen failed/unavailable. Fallback to Claude...")
                    plan_content = self.claude_invoker.invoke_for_planning(
                        action_content=content,
                        action_metadata=frontmatter
                    )
                    if plan_content: used_engine = "claude"

                elif primary_engine == "claude" and self.qwen_invoker and self.qwen_invoker.is_available:
                    self.logger.info("Claude failed/unavailable. Fallback to Qwen...")
                    plan_content = self.qwen_invoker.invoke_for_planning(
                        action_content=content,
                        action_metadata=frontmatter
                    )
                    if plan_content: used_engine = "qwen"

            # 3. Last Resort: Templates
            if not plan_content:
                self.logger.warning("All AI agents failed. Falling back to templates.")
                plan_content = self._generate_plan_logic(frontmatter, body)
                used_engine = "template"

            # Write Plan File
            action_id = frontmatter.get("id", "unknown")
            domain = str(frontmatter.get("domain") or "").strip().lower() or None
            filename = f"PLAN_{action_id}.md"
            path = vault.write_plan(filename, plan_content, domain=domain)

            self.logger.log_action(
                action_type="create_plan",
                result="success",
                target=str(path),
                details={
                    "source_action": action_id,
                    "domain": domain or "general",
                    "engine": used_engine
                }
            )

            return filename

        except Exception as e:
            self.logger.error(f"Error creating plan: {e}")
            return ""

    def _generate_plan_logic(self, meta: Dict[str, Any], body: str) -> str:
        """Template fallback logic."""
        action_type = str(meta.get("type", "unknown"))
        action_id = str(meta.get("id", "unknown"))
        source = str(meta.get("source", "unknown"))
        domain = str(meta.get("domain") or "").strip().lower() or "general"
        priority = str(meta.get("priority") or "normal").strip().lower()
        requires_approval = action_type in {"email", "message", "social", "finance", "payment", "invoice"}

        plan = f"""---
plan_id: "PLAN_{action_id}"
action_id: "{action_id}"
action_type: "{action_type}"
source: "{source}"
domain: "{domain}"
created: "{time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}"
status: "draft"
priority: "{priority}"
requires_approval: {str(requires_approval).lower()}
engine: "template"
---

# Objective
Handle incoming {action_type} from {source}.

# Steps
"""

        if action_type == "email":
            plan += self._plan_email_response(meta)
        elif action_type == "message":
            plan += self._plan_message_response(meta)
        elif action_type == "social":
            plan += self._plan_social_post(meta)
        elif action_type == "file_drop":
            plan += self._plan_file_processing(meta)
        else:
            plan += "- [ ] 1. Review Request\n"
            plan += "- [ ] 2. Determine appropriate action\n"
            plan += "- [ ] 3. Execute or request approval\n"

        plan += "\n# Notes\n"
        plan += "*Generated via template fallback (Qwen unavailable).*\n"

        return plan

    def _plan_email_response(self, meta: Dict[str, Any]) -> str:
        steps = "- [ ] 1. Analyze email content\n- [ ] 2. Draft response\n- [ ] 3. **[APPROVAL REQUIRED]** Send Reply\n- [ ] 4. Archive Email\n"
        return steps

    def _plan_message_response(self, meta: Dict[str, Any]) -> str:
        return "- [ ] 1. Read message\n- [ ] 2. Draft reply\n- [ ] 3. **[APPROVAL REQUIRED]** Send Reply\n"

    def _plan_social_post(self, meta: Dict[str, Any]) -> str:
        return "- [ ] 1. Review content\n- [ ] 2. Format for platform\n- [ ] 3. **[APPROVAL REQUIRED]** Publish Post\n"

    def _plan_file_processing(self, meta: Dict[str, Any]) -> str:
        return "- [ ] 1. Analyze file\n- [ ] 2. Process according to type\n- [ ] 3. Move to appropriate folder\n"

    def get_stats(self) -> Dict[str, Any]:
        return {
            "claude_available": bool(self.claude_invoker and self.claude_invoker.is_available),
            "qwen_available": bool(self.qwen_invoker and self.qwen_invoker.is_available)
        }


if __name__ == "__main__":
    pm = PlanManager()
    print(f"Stats: {pm.get_stats()}")
